# Generated by Django 5.2.3 on 2026-02-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.TextField(blank=True, max_length=100)),
                ('title', models.TextField(blank=True, max_length=100)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('prep_time', models.IntegerField(blank=True, help_text='Minutes', null=True)),
                ('cook_time', models.IntegerField(blank=True, help_text='Minutes', null=True)),
                ('total_time', models.IntegerField(blank=True, help_text='Minutes', null=True)),
                ('description', models.TextField(blank=True)),
                ('nutrients', models.JSONField(blank=True, null=True)),
                ('serves', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
    ]
